---
title: "Assignment 2"
subtitle: |
  Data Acquisition and Survey Methods  
  Survey Analysis Report
author: |
  Group 39
date: "2026"
output:
  pdf_document:
    toc: true
    number_sections: true
---

------------------------------------------------------------------------

# Introduction

Survey data analysis, report & presentation:

Exploratory Data Analysis: Choose appropriate methods to explore the categorical and quantitative features in your data set (one visualization per research question). Briefly explain the methods and comment on your findings.
Descriptive Inference: Compute suitable summary statistics and display the results in a table.
Analytic Inference: Select an appropriate test statistic to test your hypothesis. Summarize the results and explain how your findings are connected to your research question.
Guidelines for the presentation:

The survey results are given below. Use these to extract the data to analyze the research questions posed by your own group.
The participation of all group members is mandatory and everyone should present.
introduce the survey questions and present the results using appropriate visualizations
stay within the time limit of 5 minutes, cover all questions, and use suitable visuals
use any presentation tool such as PowerPoint or LaTeX Beamer, and submit the slides together with your final report
The presentation will not be graded separately, but is a condition for a positive grade. If you are between grades, a good presentation will lead to a better grade.
Guidelines for the report:

use RMarkdown
include a table of contents
briefly summarize the functions used
display all important code snippets in the .pdf
document your findings
Submit both the .rmd and .pdf files for your report and the slides of your group presentation (.pdf) via TUWEL.